# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bot_pb2 as bot__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/bot.Bot/SubmitOrder',
                request_serializer=bot__pb2.SubmitOrderRequest.SerializeToString,
                response_deserializer=bot__pb2.SubmitOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/bot.Bot/CancelOrder',
                request_serializer=bot__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=bot__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/bot.Bot/GetOrderStatus',
                request_serializer=bot__pb2.GetOrderStatusRequest.SerializeToString,
                response_deserializer=bot__pb2.OrderStatusResponse.FromString,
                _registered_method=True)
        self.GetTokenInfo = channel.unary_unary(
                '/bot.Bot/GetTokenInfo',
                request_serializer=bot__pb2.GetTokenInfoRequest.SerializeToString,
                response_deserializer=bot__pb2.TokenInfoResponse.FromString,
                _registered_method=True)
        self.GetPortfolioSummary = channel.unary_unary(
                '/bot.Bot/GetPortfolioSummary',
                request_serializer=bot__pb2.Empty.SerializeToString,
                response_deserializer=bot__pb2.PortfolioSummaryResponse.FromString,
                _registered_method=True)
        self.StreamOrders = channel.unary_stream(
                '/bot.Bot/StreamOrders',
                request_serializer=bot__pb2.StreamOrdersRequest.SerializeToString,
                response_deserializer=bot__pb2.OrderUpdate.FromString,
                _registered_method=True)


class BotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolioSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=bot__pb2.SubmitOrderRequest.FromString,
                    response_serializer=bot__pb2.SubmitOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=bot__pb2.CancelOrderRequest.FromString,
                    response_serializer=bot__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=bot__pb2.GetOrderStatusRequest.FromString,
                    response_serializer=bot__pb2.OrderStatusResponse.SerializeToString,
            ),
            'GetTokenInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenInfo,
                    request_deserializer=bot__pb2.GetTokenInfoRequest.FromString,
                    response_serializer=bot__pb2.TokenInfoResponse.SerializeToString,
            ),
            'GetPortfolioSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolioSummary,
                    request_deserializer=bot__pb2.Empty.FromString,
                    response_serializer=bot__pb2.PortfolioSummaryResponse.SerializeToString,
            ),
            'StreamOrders': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrders,
                    request_deserializer=bot__pb2.StreamOrdersRequest.FromString,
                    response_serializer=bot__pb2.OrderUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bot.Bot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bot.Bot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot.Bot/SubmitOrder',
            bot__pb2.SubmitOrderRequest.SerializeToString,
            bot__pb2.SubmitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot.Bot/CancelOrder',
            bot__pb2.CancelOrderRequest.SerializeToString,
            bot__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot.Bot/GetOrderStatus',
            bot__pb2.GetOrderStatusRequest.SerializeToString,
            bot__pb2.OrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot.Bot/GetTokenInfo',
            bot__pb2.GetTokenInfoRequest.SerializeToString,
            bot__pb2.TokenInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolioSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot.Bot/GetPortfolioSummary',
            bot__pb2.Empty.SerializeToString,
            bot__pb2.PortfolioSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bot.Bot/StreamOrders',
            bot__pb2.StreamOrdersRequest.SerializeToString,
            bot__pb2.OrderUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
